In [ ]:
#import load_model class for loading h5 file
from tensorflow.keras.models import load_model
#import image class to process the images
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
import numpy as np

In [ ]:
#load saved model file
model=load_model('Updated-Xception-diabetic-retinopathy.h5')

In [ ]:
#load one random image from local system
img=image.load_img(r'PDR.jpg',target_size=(299,299))

In [ ]:
#convert image to array format
x=image.img_to_array(img)

In [ ]:
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 299, 299, 3)

In [ ]:
model.predict(img_data)

1/1 [==============================] - 2s 2s/step


array([[1.40166845e-11, 8.72857253e-09, 1.59445044e-08, 3.99780248e-07,
        9.99999523e-01]], dtype=float32)

In [ ]:
output=np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 392ms/step


In [ ]:
output==0,output==1,output==2,output==3,output==4

(array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([ True]))

In [ ]:
index=['No Diabetic Retinopathy', 'Mild DR', 'Moderate DR', 'Severe DR', 'Proliferative DR']
result = str(index[output[0]])
result

'Proliferative DR'